name: Deploy to Local S3 (Floci)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # Ini menandakan perintah dijalankan di komputermu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload to Local S3
        run: |
          aws --endpoint-url http://127.0.0.1:4566 s3 cp index.html s3://portofolio-ku/index.html
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
      - name: Upload to Local S3 & Invalidate Cache
        run: |
          aws --endpoint-url http://127.0.0.1:4566 s3 cp index.html s3://portofolio-ku/index.html
          aws --endpoint-url http://127.0.0.1:4566 cloudfront create-invalidation --distribution-id E0MDQCEP9PFHNU --paths "/*"
